<div class="container-fluid" ng-controller="TabsController">
    <div class="row">   
        <div class="col-sm-offset-2 col-sm-8">
            
    <div class="panel panel-default">
        <div class="panel-body">
            <tab-widget>
                <tab-pane title="Skill">
                    <div class="row">
                        <div class="col-sm-12">
                            <h4>Skill</h4>
                            <ul>
                                <li><p>PHP</p></li>
                                <li><p>js, jquery, angularjs</p></li>
                                <li><p>html, css, bootstrap, responsive web design</p></li>
                                <li><p>mysql</p></li>
                                <li><p>MVC, Restful</p></li>
                            </ul>
                        </div>
                    </div>
                </tab-pane>
                <tab-pane title="Experience">
                    <div class="row">
                        <div class="col-sm-12">
                            <h4>Software Developer in iLearn Sdn.Bhd. 2012-2014</h4>
                            <ul>
                                <li><p>Responsible for CRM system.</p></li>
                                <li><p>Modified the CRM System to suite the customer need. The CRM System<br>
                                        is fully written in PHP.</p></li>
                                <li><p>Customized Accounting Software by writing scripting and plugin.</p></li>
                            </ul>
                        </div>
                        <div class="col-sm-12 underline"></div>
                        <div class="clearfix"></div>
                        <div class="col-sm-12">
                            <h4>Physical Custom Layout in Intel(M) Sdn.Bhd. 2010-2012</h4>
                            <ul>
                                <li><p>Software Support for Custom Layout Team.</p></li>
                                <li><p>Design Regression Flow using perl and tcl.</p></li>
                            </ul>
                        </div>
                    </div>
                   
                </tab-pane>
<!--                <tab-pane title="tab 3">
                    <h4>Tab 3</h4>
                    <p>on tab widget</p>
                </tab-pane>
                <tab-pane title="tab 4">
                    <h4>Tab 4</h4>
                    <div class="container-fluid">
                        <div text-angular="text-angular" name="htmlcontent" ng-model="htmlcontent" ta-disabled='disabled'></div>
                    </div>
                </tab-pane>-->
            </tab-widget>
        </div>
    </div>
            
        </div>
    </div>
</div>